---
title: "データサイエンス"
toc: false
---

千葉大学 総合国際学位プログラムの授業

担当教員：[ニッタ ジョエル](https://www.joelnitta.com)

## 概要

データ解析は、理系だけではなく、文系も含めた多くの学問分野で使われるようになっている。本授業では、特に大学院生の研究に応用できるようにデータサイエンスの基本的なスキルとツールを学ぶ。主に「R」プログラミング言語を使用するが、大学院生のニーズに合わせて、必要なツールがあれば適宜授業の内容に加える。

## 教科書

- [R for Data Science (2nd Edition) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund](https://r4ds.hadley.nz)
  - アマゾンには[第１エディションの翻訳](https://www.amazon.co.jp/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_2?crid=1LT40JGBKBE7B&dib=eyJ2IjoiMSJ9.Z1c-Zpi4mNudjpLRyuLhducKMb-YhxP24EK3mPHAaT5H6I_YQpDy0ZiscWF82DKAikv-M7lwWejexO95nHjrlzYnimhuR5TsrxMqJ3xzzyKt-MpXmv7F4blKBfY6qX0DfUN_PQ-4bl6CejwCLucudSL95GZMCfZGbLEHNQzcCtIwaeIVUebyC3vIlTf1_GfvpTEAISm-kZsSQBfO17vhW1IJe4k7PVF8dZBIg34EoKM7QPySNJp31Yfe3RXF3H_OJPWCLD9Dey5YK2b6F4TRs1xOFYECtZv25z83hy9-2fc.rr3weMHRTFsoSsue9htecVJLWPkGRlrwYtOb_p6g5Pg&dib_tag=se&keywords=r+for+data+science+2e&qid=1712609538&sprefix=R+for+data+science%2Caps%2C495&sr=8-2)がある

## スケジュール

毎週のリーディングを講義の**前に**読んでください。

（全ての講義の録画はありません）

- 第1回（2025-04-15）: **ガイダンス、データサイエンスとR入門**
  - [スライド](day1/index.qmd)
  - リーディング
    - [R4DS Introduction](https://r4ds.hadley.nz/intro)
    - [R4DS Chapter 2 (Workflow: Basics)](https://r4ds.hadley.nz/workflow-basics)
- 第2回（2025-04-22）: **プロジェクトの整理とデータの読み込み**
  - [スライド](day2/index.qmd)
  - リーディング
    - [R4DS Chapter 6 (Workflow: Scripts and Projects)](https://r4ds.hadley.nz/workflow-scripts)
    - [R4DS Chapter 7 (Data Import)](https://r4ds.hadley.nz/data-import)
- 第3回（2025-04-30）: **データの整理（１）**
  - [スライド](day3/index.qmd)
  - リーディング
    - [R4DS Chapter 3 (Data Transformation)](https://r4ds.hadley.nz/)
- 第4回（2025-05-09）: **データの整理（２）**
  - [スライド](day4/index.qmd)
  - リーディング
    - [R4DS Chapter 5 (Data Tidying)](https://r4ds.hadley.nz/data-tidy)
    - [R4DS Chapter 19 (Joins)](https://r4ds.hadley.nz/joins)
- 第5回（2025-05-13）: **データの可視化**
  - [スライド](day5/index.qmd)
  - リーディング
    - [R4DS Chapter 1 (Data Visualization)](https://r4ds.hadley.nz/data-visualize)
- 第6回（2025-05-20）: **再現可能な文書の書き方**
  - [スライド](day6/index.qmd)
  - リーディング
    - [R4DS Chapter 28 (Quarto)](https://r4ds.hadley.nz/quarto)
- 第7回（2025-05-27）: **レポートの発表、再現可能なデータ解析のベストプラクティス**
  - [スライド](day7/index.qmd)
- オンデマンド回: **生成AIの基本**
  - [スライド](https://joelnitta.github.io/joho-shori/on-demand)
  - [資料：中部大学「ChatGPTについて」](https://edu.isc.chubu.ac.jp/hsuzuki/iip/DataScience/ChatGPT/chatgpt.html)
  - [録画](https://www.youtube.com/watch?v=ok837FBoEI8)

## オフィスアワー

予約制（<joelnitta@chiba-u.jp>までメールにて連絡ください）。対面・非対面での相談、ご希望とご都合に合わせて対応いたします。

## リンク

- [シラバス](https://syllabus.gs.chiba-u.jp/2025/211218201000000/Z021100201/ja_JP)
